### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by weizhangCoder** [LinXunFeng/LXFFM#1]
开始转swift多久了

**Comment by LinXunFeng** [comment]
半年前就转Swift了，不过是Swift 2.x的，而且做了几个项目都是用OC，Swift都忘得差不多了，所以现在花9天来做这个项目来适应一下Swift 3.0

**Comment by cheshuangchun** [comment]
9天就做完啦？牛逼啊。现在swift用的广泛吗？

**Comment by LinXunFeng** [comment]
是否广泛我就不知道了，不过我听说现在很多公司在逐步转为Swift开发了，这是个趋势，多学点没坏处

**Comment by JackYangZhi** [comment]
我的运行不起来，pod出错了，我打开别的项目pod没问题！

**Comment by LinXunFeng** [comment]
@JackYangZhi 我用原版Xcode8打开也没问题呀，或许你可以试下升级你的cocoapods

**Comment by JackYangZhi** [comment]
我的cocoapods是1.1.1的

**Comment by LinXunFeng** [comment]
@JackYangZhi 现在应该没问题，解决办法可以看下README.md

**Comment by carlosbdw** [comment]
xcode8.2， pod1.1.1  pod install以后报错

diff: /Users/my/GitHub/LXFFM/LXFFM/Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
