### ISSUE TITLE
xcode8.2， pod1.1.1 pod install以后报错

### ISSUE THREAD

**Issue by carlosbdw** [LinXunFeng/LXFFM#2]
diff: /Users/my/GitHub/LXFFM/LXFFM/Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by LinXunFeng** [comment]
@carlosbdw 我重新下载下来试了一下，先pod install，等它执行完毕后关掉再打开LXFFM.xcworkspace，编译，没有任何问题，环境是跟你一样的。我试过先直接编译就会报你写的这个错误。你出现这个应该是你还没有完成pod install
